version: "3.8"

services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/brazilianstars
    command: sh -c "npx prisma migrate dev --name init && npm run dev"
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=brazilianstars
    restart: unless-stopped

volumes:
  postgres_data:
